source 'https://rubygems.org'

gem "bigdecimal"
gem "bundler-unload"
gem "builder"
gem "colored"
gem "cri"
gem "execjs"
gem "kramdown"
gem "nanoc"
gem "nanoc-cachebuster"
gem 'nanoc-gzip-filter'
gem "nanoc-toolbox"
gem "rainpress"
gem "slim"
gem "therubyracer"
gem "uglifier"
gem "w3c_validators"
gem "yuicompressor"
